
export default new Map([
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/garden/designing-core/en.md", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fgarden%2Fdesigning-core%2Fen.md&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/garden/designing-core/es.md", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fgarden%2Fdesigning-core%2Fes.md&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/garden/limonysal/en.md", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fgarden%2Flimonysal%2Fen.md&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/garden/limonysal/es.md", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fgarden%2Flimonysal%2Fes.md&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/geography/first-journey/en.md", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fgeography%2Ffirst-journey%2Fen.md&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/geography/first-journey/es.md", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fgeography%2Ffirst-journey%2Fes.md&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/pages/cv/en.md", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fpages%2Fcv%2Fen.md&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/pages/cv/es.md", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fpages%2Fcv%2Fes.md&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/pages/home/en.md", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fpages%2Fhome%2Fen.md&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/pages/home/es.md", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fpages%2Fhome%2Fes.md&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/pages/philosophy/en.md", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fpages%2Fphilosophy%2Fen.md&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/pages/philosophy/es.md", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fpages%2Fphilosophy%2Fes.md&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/posts/comprehensible-input-strategies/en.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fposts%2Fcomprehensible-input-strategies%2Fen.mdx&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/posts/humanity-in-check/en.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fposts%2Fhumanity-in-check%2Fen.mdx&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/posts/humanity-in-check/es.md", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fposts%2Fhumanity-in-check%2Fes.md&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/posts/interactive-multimedia/en.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fposts%2Finteractive-multimedia%2Fen.mdx&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/posts/interactive-multimedia/es.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fposts%2Finteractive-multimedia%2Fes.mdx&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/posts/multimodal-pedagogy/en.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fposts%2Fmultimodal-pedagogy%2Fen.mdx&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/posts/multimodal-pedagogy/es.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fposts%2Fmultimodal-pedagogy%2Fes.mdx&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/posts/natural-induction/en.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fposts%2Fnatural-induction%2Fen.mdx&astroContentModuleFlag=true")],
["/Users/mac/Documents/01_ProyectoEspanol/SergioUribe.co/website/github/sergiouribeco/src/content/posts/somatic-enactivism/en.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=%2FUsers%2Fmac%2FDocuments%2F01_ProyectoEspanol%2FSergioUribe.co%2Fwebsite%2Fgithub%2Fsergiouribeco%2Fsrc%2Fcontent%2Fposts%2Fsomatic-enactivism%2Fen.mdx&astroContentModuleFlag=true")]]);
		